spring.application.name=recipe-sharing
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_sharing
spring.datasource.username=postgres
spring.datasource.password=PostgreSql-226

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true